/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "receiver.h"
#include "receiver_aliases.h"
#include "trigger.h"
#include "trigger_aliases.h"
#include "isr.h"
#include "LCD_Char.h"
#include "Clock.h"
#include "Timer.h"
#include "ADC_SAR_Seq.h"
#include "IR_L.h"
#include "IR_L_aliases.h"
#include "IR_R.h"
#include "IR_R_aliases.h"
#include "AMux.h"
#include "Clock_2.h"
#include "PWM_OUT1.h"
#include "PWM_OUT1_aliases.h"
#include "Clock_3.h"
#include "PWM_OUT2.h"
#include "PWM_OUT2_aliases.h"
#include "PWM_1.h"
#include "PWM_2.h"
#include "ButtonL.h"
#include "ButtonL_aliases.h"
#include "ButtonR.h"
#include "ButtonR_aliases.h"
#include "QuadDec_1.h"
#include "QuadDec_2.h"
#include "Encoder_1.h"
#include "Encoder_1_aliases.h"
#include "Encoder_2.h"
#include "Encoder_2_aliases.h"
#include "Clock_4.h"
#include "Clock_5.h"
#include "Encoder_3.h"
#include "Encoder_3_aliases.h"
#include "Encoder_4.h"
#include "Encoder_4_aliases.h"
#include "LCD_Char_LCDPort.h"
#include "LCD_Char_LCDPort_aliases.h"
#include "ADC_SAR_Seq_IRQ.h"
#include "ADC_SAR_Seq_intClock.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

